[dependencies.stm32f7]
repository = "https://github.com/STMicroelectronics/stm32f7xx_hal_driver.git"
tag = "v1.3.1"

[dependencies.cmsis_device_f7]
repository = "https://github.com/STMicroelectronics/cmsis_device_f7.git"
tag = "v1.2.9"

[dependencies.cmsis6]
repository = "https://github.com/ARM-software/CMSIS_6.git"
tag = "v6.1.0"

[toolchains.stm32]
container = "renemoll/builder_arm_gcc"
# additional_options.configuration = "-G Ninja"
toolchain_file = "bob-cmake/toolchains/toolchain_cortex-m7_fpu_dp.cmake"

[targets.stm32f7]
toolchain = "stm32"
# additional_options.configuration = "-DSTM32F767xx"
